name: tennis-rest-service
services:
    webapp:
        image: node-api-webapp:local
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "4000:3000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        deploy:
            resources:
                reservations:
                    cpus: 1
                    memory: 1024m
    redis:
        image: redis:local
        build:
            context: ./
            dockerfile: Dockerfile_redis
        ports:
            - "8379:6379"
        deploy:
            resources:
                reservations:
                    cpus: 1
                    memory: 1024m